/*
 * Copyright (C) 2026 The FlorisBoard Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.patrickgold.florisboard.ime.nlp.plugin

/**
 * An identifier generated by the host. It identifies a lifecycle operation without carrying
 * provider, editor, candidate, dictionary, or user-entered content.
 */
@JvmInline
internal value class AutocorrectPluginDiagnosticId private constructor(val value: Long) {
    companion object {
        val None = AutocorrectPluginDiagnosticId(0L)

        fun fromHostId(value: Long) = AutocorrectPluginDiagnosticId(value.coerceAtLeast(0L))
    }
}

internal enum class AutocorrectPluginDiagnosticOperation {
    SUGGESTION,
    FINISH_SESSION,
    REMOVE_CANDIDATE,
    PLUGIN_UI,
    USER_DICTIONARY,
    UNKNOWN_REPLY,
}

internal enum class AutocorrectPluginDiagnosticState {
    STARTED,
    SUCCEEDED,
    FAILED,
    REJECTED,
    CANCELLED,
    CONNECTED,
    DISCONNECTED,
    CLEARED,
    ACKNOWLEDGED,
}

internal enum class AutocorrectPluginDiagnosticError {
    NONE,
    PROVIDER_NOT_FOUND,
    QUERY_FAILED,
    BIND_REJECTED,
    NULL_BINDING,
    SERVICE_DISCONNECTED,
    BINDING_DIED,
    DEAD_REMOTE,
    REMOTE_FAILURE,
    STALE_BINDING,
    STALE_SESSION,
    STALE_GENERATION,
    UNAUTHORIZED_SENDER,
    NOT_CONNECTED,
    UNKNOWN_REQUEST,
    SUPERSEDED,
    SEND_FAILED,
    MALFORMED_MESSAGE,
    INVALID_REQUEST,
    OPERATION_UNAVAILABLE,
    ACCESS_DENIED,
}

/**
 * Deliberately coarse latency buckets. Exact timestamps are neither retained nor exported.
 */
internal enum class AutocorrectPluginDiagnosticDuration {
    UNKNOWN,
    UNDER_1_MS,
    FROM_1_TO_4_MS,
    FROM_5_TO_15_MS,
    FROM_16_TO_49_MS,
    FROM_50_TO_149_MS,
    FROM_150_TO_499_MS,
    FROM_500_TO_1_999_MS,
    AT_LEAST_2_SECONDS,
}

/**
 * Closed diagnostic event model. None of the event types can hold arbitrary text or exceptions.
 */
internal sealed interface AutocorrectPluginDiagnosticEvent {
    data class Discovery(
        val state: AutocorrectPluginDiagnosticState,
        val duration: AutocorrectPluginDiagnosticDuration,
        val providerCount: Int,
        val error: AutocorrectPluginDiagnosticError,
    ) : AutocorrectPluginDiagnosticEvent

    data class Binding(
        val bindingEpoch: Long,
        val state: AutocorrectPluginDiagnosticState,
        val error: AutocorrectPluginDiagnosticError,
    ) : AutocorrectPluginDiagnosticEvent

    data class Session(
        val bindingEpoch: Long,
        val sessionId: AutocorrectPluginDiagnosticId,
        val state: AutocorrectPluginDiagnosticState,
        val error: AutocorrectPluginDiagnosticError,
    ) : AutocorrectPluginDiagnosticEvent

    data class Operation(
        val bindingEpoch: Long,
        val sessionId: AutocorrectPluginDiagnosticId,
        val requestId: AutocorrectPluginDiagnosticId,
        val operation: AutocorrectPluginDiagnosticOperation,
        val state: AutocorrectPluginDiagnosticState,
        val duration: AutocorrectPluginDiagnosticDuration,
        val itemCount: Int,
        val error: AutocorrectPluginDiagnosticError,
    ) : AutocorrectPluginDiagnosticEvent

    data class ReplyRejected(
        val bindingEpoch: Long,
        val operation: AutocorrectPluginDiagnosticOperation,
        val error: AutocorrectPluginDiagnosticError,
    ) : AutocorrectPluginDiagnosticEvent
}

internal data class AutocorrectPluginDiagnosticRecord(val sequence: Long, val event: AutocorrectPluginDiagnosticEvent)

internal data class AutocorrectPluginDiagnosticSnapshot(
    val records: List<AutocorrectPluginDiagnosticRecord>,
    val droppedRecordCount: Long,
)

/**
 * A bounded, thread-safe in-memory history intended for a future developer diagnostics screen.
 *
 * Operation start times live only until completion and are converted to coarse duration buckets.
 * The public snapshot has no wall-clock or monotonic timestamps.
 */
internal class AutocorrectPluginDiagnostics(
    private val capacity: Int = DEFAULT_CAPACITY,
    private val monotonicNanos: () -> Long = System::nanoTime,
) {
    private data class OperationKey(
        val operation: AutocorrectPluginDiagnosticOperation,
        val sessionId: AutocorrectPluginDiagnosticId,
        val requestId: AutocorrectPluginDiagnosticId,
    )

    private val records = ArrayDeque<AutocorrectPluginDiagnosticRecord>(capacity)
    private val operationStarts = mutableMapOf<OperationKey, Long>()
    private var discoveryStartedAtNanos: Long? = null
    private var nextSequence = 1L
    private var droppedRecordCount = 0L

    init {
        require(capacity > 0) { "Diagnostic capacity must be positive" }
    }

    @Synchronized
    fun record(event: AutocorrectPluginDiagnosticEvent) {
        if (records.size == capacity) {
            records.removeFirst()
            droppedRecordCount++
        }
        records.addLast(
            AutocorrectPluginDiagnosticRecord(
                sequence = nextSequence++,
                event = event,
            ),
        )
    }

    @Synchronized
    fun discoveryStarted() {
        discoveryStartedAtNanos = monotonicNanos()
        record(
            AutocorrectPluginDiagnosticEvent.Discovery(
                state = AutocorrectPluginDiagnosticState.STARTED,
                duration = AutocorrectPluginDiagnosticDuration.UNKNOWN,
                providerCount = 0,
                error = AutocorrectPluginDiagnosticError.NONE,
            ),
        )
    }

    @Synchronized
    fun discoveryFinished(providerCount: Int, error: AutocorrectPluginDiagnosticError) {
        val duration = discoveryStartedAtNanos?.let { start ->
            diagnosticDurationForNanos((monotonicNanos() - start).coerceAtLeast(0L))
        } ?: AutocorrectPluginDiagnosticDuration.UNKNOWN
        discoveryStartedAtNanos = null
        record(
            AutocorrectPluginDiagnosticEvent.Discovery(
                state = if (error == AutocorrectPluginDiagnosticError.NONE) {
                    AutocorrectPluginDiagnosticState.SUCCEEDED
                } else {
                    AutocorrectPluginDiagnosticState.FAILED
                },
                duration = duration,
                providerCount = providerCount.coerceIn(0, MAX_ITEM_COUNT),
                error = error,
            ),
        )
    }

    @Synchronized
    fun operationStarted(
        operation: AutocorrectPluginDiagnosticOperation,
        bindingEpoch: Long,
        sessionId: Long = 0L,
        requestId: Long = 0L,
    ) {
        val safeSessionId = AutocorrectPluginDiagnosticId.fromHostId(sessionId)
        val safeRequestId = AutocorrectPluginDiagnosticId.fromHostId(requestId)
        val key = OperationKey(
            operation = operation,
            sessionId = safeSessionId,
            requestId = safeRequestId,
        )
        if (key !in operationStarts && operationStarts.size == capacity) {
            operationStarts.keys.iterator().let { iterator ->
                if (iterator.hasNext()) {
                    iterator.next()
                    iterator.remove()
                }
            }
        }
        operationStarts[key] = monotonicNanos()
        record(
            AutocorrectPluginDiagnosticEvent.Operation(
                bindingEpoch = bindingEpoch.coerceAtLeast(0L),
                sessionId = safeSessionId,
                requestId = safeRequestId,
                operation = operation,
                state = AutocorrectPluginDiagnosticState.STARTED,
                duration = AutocorrectPluginDiagnosticDuration.UNKNOWN,
                itemCount = 0,
                error = AutocorrectPluginDiagnosticError.NONE,
            ),
        )
    }

    @Synchronized
    fun operationFinished(
        operation: AutocorrectPluginDiagnosticOperation,
        bindingEpoch: Long,
        sessionId: Long = 0L,
        requestId: Long = 0L,
        state: AutocorrectPluginDiagnosticState,
        itemCount: Int = 0,
        error: AutocorrectPluginDiagnosticError = AutocorrectPluginDiagnosticError.NONE,
    ) {
        var safeSessionId = AutocorrectPluginDiagnosticId.fromHostId(sessionId)
        val safeRequestId = AutocorrectPluginDiagnosticId.fromHostId(requestId)
        val requestedKey = OperationKey(
            operation = operation,
            sessionId = safeSessionId,
            requestId = safeRequestId,
        )
        val actualKey = if (requestedKey in operationStarts) {
            requestedKey
        } else {
            operationStarts.keys.firstOrNull { key ->
                key.operation == operation && key.requestId == safeRequestId
            }
        }
        if (actualKey != null) safeSessionId = actualKey.sessionId
        val startedAt = actualKey?.let(operationStarts::remove)
        val duration = startedAt?.let { start ->
            diagnosticDurationForNanos((monotonicNanos() - start).coerceAtLeast(0L))
        } ?: AutocorrectPluginDiagnosticDuration.UNKNOWN
        record(
            AutocorrectPluginDiagnosticEvent.Operation(
                bindingEpoch = bindingEpoch.coerceAtLeast(0L),
                sessionId = safeSessionId,
                requestId = safeRequestId,
                operation = operation,
                state = state,
                duration = duration,
                itemCount = itemCount.coerceIn(0, MAX_ITEM_COUNT),
                error = error,
            ),
        )
    }

    @Synchronized
    fun snapshot() = AutocorrectPluginDiagnosticSnapshot(
        records = records.toList(),
        droppedRecordCount = droppedRecordCount,
    )

    companion object {
        const val DEFAULT_CAPACITY = 256
        private const val MAX_ITEM_COUNT = 10_000
    }
}

private const val NANOS_PER_MILLISECOND = 1_000_000L
private const val FIVE_MILLISECONDS = 5L
private const val SIXTEEN_MILLISECONDS = 16L
private const val FIFTY_MILLISECONDS = 50L
private const val ONE_HUNDRED_FIFTY_MILLISECONDS = 150L
private const val FIVE_HUNDRED_MILLISECONDS = 500L
private const val TWO_SECONDS_IN_MILLISECONDS = 2_000L

internal fun diagnosticDurationForNanos(nanos: Long): AutocorrectPluginDiagnosticDuration {
    val millis = nanos.coerceAtLeast(0L) / NANOS_PER_MILLISECOND
    return when {
        millis < 1L -> AutocorrectPluginDiagnosticDuration.UNDER_1_MS

        millis < FIVE_MILLISECONDS -> AutocorrectPluginDiagnosticDuration.FROM_1_TO_4_MS

        millis < SIXTEEN_MILLISECONDS -> AutocorrectPluginDiagnosticDuration.FROM_5_TO_15_MS

        millis < FIFTY_MILLISECONDS -> AutocorrectPluginDiagnosticDuration.FROM_16_TO_49_MS

        millis < ONE_HUNDRED_FIFTY_MILLISECONDS ->
            AutocorrectPluginDiagnosticDuration.FROM_50_TO_149_MS

        millis < FIVE_HUNDRED_MILLISECONDS ->
            AutocorrectPluginDiagnosticDuration.FROM_150_TO_499_MS

        millis < TWO_SECONDS_IN_MILLISECONDS ->
            AutocorrectPluginDiagnosticDuration.FROM_500_TO_1_999_MS

        else -> AutocorrectPluginDiagnosticDuration.AT_LEAST_2_SECONDS
    }
}
