/*
 * Copyright (C) 2026 The FlorisBoard Contributors
 * SPDX-License-Identifier: Apache-2.0
 * Modified in Better FlorisBoard: license header standardized.
 */

package dev.patrickgold.florisboard.ime.media.emoji

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.io.File
import java.security.MessageDigest

class EmojiRootAssetTest :
    FunSpec({
        test("derived root asset matches the original generated file") {
            val emojiAssetRoot = requireNotNull(System.getProperty("florisboard.emojiLocaleAssetRoot")) {
                "Generated emoji asset root was not configured"
            }
            val englishAsset = File(emojiAssetRoot, "en.txt")
            val digest = MessageDigest.getInstance("SHA-256")
            englishAsset.forEachLine(Charsets.UTF_8) { line ->
                digest.update(rootEmojiAssetLine(line).toByteArray(Charsets.UTF_8))
                digest.update('\n'.code.toByte())
            }
            val actual = digest.digest().joinToString("") { "%02x".format(it.toInt() and 0xff) }

            // SHA-256 of the former bundled root.txt, including its final newline.
            actual shouldBe "a4570f188a46b06e05205479fb6c8802be8c7be8cb0bee92d1fc4d7fbc92522a"
        }

        test("root projection drops semicolons in localized metadata without changing emoji rows") {
            rootEmojiAssetLine("[people_body]") shouldBe "[people_body]"
            rootEmojiAssetLine("# Auto-generated by emojicon.py using CLDR v48") shouldBe
                "# Auto-generated by emojicon.py using CLDR v48"
            rootEmojiAssetLine("\t🫰🏻;hand with index finger and thumb crossed;&lt;3|heart") shouldBe "\t🫰🏻;;"
        }
    })
