/*
 * Copyright (C) 2026 The FlorisBoard Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.patrickgold.florisboard.ime.media.emoji

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.io.File
import java.security.MessageDigest

class EmojiRootAssetTest : FunSpec({
    test("derived root asset matches the original generated file") {
        val englishAsset = sequenceOf("src/main/assets", "app/src/main/assets")
            .map { File(it, "ime/media/emoji/en.txt") }
            .first { it.isFile }
        val digest = MessageDigest.getInstance("SHA-256")
        englishAsset.forEachLine(Charsets.UTF_8) { line ->
            digest.update(rootEmojiAssetLine(line).toByteArray(Charsets.UTF_8))
            digest.update('\n'.code.toByte())
        }
        val actual = digest.digest().joinToString("") { "%02x".format(it.toInt() and 0xff) }

        // SHA-256 of the former bundled root.txt, including its final newline.
        actual shouldBe "a4570f188a46b06e05205479fb6c8802be8c7be8cb0bee92d1fc4d7fbc92522a"
    }

    test("root projection drops semicolons in localized metadata without changing emoji rows") {
        rootEmojiAssetLine("[people_body]") shouldBe "[people_body]"
        rootEmojiAssetLine("# Auto-generated by emojicon.py using CLDR v48") shouldBe
            "# Auto-generated by emojicon.py using CLDR v48"
        rootEmojiAssetLine("\t🫰🏻;hand with index finger and thumb crossed;&lt;3|heart") shouldBe "\t🫰🏻;;"
    }
})
