/*
 * Copyright (C) 2025 The FlorisBoard Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.florisboard.lib.snygg

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.florisboard.lib.kotlin.io.writeJson
import org.florisboard.lib.kotlin.simpleNameOrEnclosing
import org.florisboard.lib.snygg.value.SnyggKeywordValueSpec
import org.florisboard.lib.snygg.value.SnyggValueEncoder
import org.florisboard.lib.snygg.value.SnyggValueSpec
import java.io.File

object SnyggJsonSchemaGenerator {
    @OptIn(ExperimentalSerializationApi::class)
    @JvmStatic
    fun main(args: Array<String>) {
        val jsonSchemaFile = File(
            args.getOrElse(0) { error("No schema output path provided.") },
        )
        jsonSchemaFile.parentFile?.let { parent ->
            check(parent.mkdirs() || parent.isDirectory) {
                "Unable to create the schema output directory."
            }
        }
        val spec = SnyggSpec

        val jsonSchema = mapWithoutEmptyValuesOf(
            "\$schema" to "https://json-schema.org/draft/2020-12/schema",
            "\$id" to SnyggStylesheet.SCHEMA_V2,
            "\$comment" to "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
            "title" to spec.meta.title,
            "description" to spec.meta.description,
            "type" to "object",
            "properties" to mapOf(
                "\$schema" to mapOf(
                    "type" to "string",
                    "const" to SnyggStylesheet.SCHEMA_V2,
                ),
            ),
            "patternProperties" to buildMap {
                for ((ruleDecl, _) in spec.annotationSpecs) {
                    put(ruleDecl.pattern.toString(), mapOf(
                        "\$ref" to "#/\$defs/${ruleDecl.propertySetId()}",
                    ))
                }
                put(SnyggElementRule.pattern.toString(), mapOf(
                    "\$ref" to "#/\$defs/${SnyggElementRule.propertySetId()}",
                ))
            },
            "additionalProperties" to false,
            "\$defs" to buildMap {
                spec.allEncoders.forEach { encoder ->
                    put(encoder.id(), encoder.schema())
                }
                for ((ruleDecl, propertySetSpec) in spec.annotationSpecs) {
                    put(ruleDecl.propertySetId(), convertToSchema(propertySetSpec))
                }
                put(SnyggElementRule.propertySetId(), convertToSchema(spec.elementsSpec))
            },
        )

        val jsonSchemaObj = convertToJsonObject(jsonSchema)
        jsonSchemaFile.writeJson(jsonSchemaObj, Json {
            prettyPrint = true
            prettyPrintIndent = "  "
        })
    }

    private fun SnyggSpecDecl.RuleDecl.propertySetId(): String {
        return "snygg-${name}-property-set"
    }

    private fun convertToJsonObject(map: Map<String, Any?>): JsonObject {
        return JsonObject(map.mapValues { (_, value) -> value.toJsonElement() })
    }

    private fun Any?.toJsonElement(): JsonElement {
        return when (this) {
            is Map<*, *> -> JsonObject(entries.associate { (key, value) ->
                check(key is String) { "JSON schema keys must be strings." }
                key to value.toJsonElement()
            })
            is List<*> -> JsonArray(map { it.toJsonElement() })
            is String -> JsonPrimitive(this)
            is Boolean -> JsonPrimitive(this)
            else -> error("Unknown JSON schema value.")
        }
    }

    private fun convertToSchema(props: SnyggSpecDecl.PropertySet): Map<String, Any> {
        return when (props.type) {
            SnyggSpecDecl.PropertySet.Type.SINGLE_SET -> (
                mapWithoutEmptyValuesOf(
                    "title" to props.meta.title,
                    "description" to props.meta.description,
                ) + props.objectSchema()
            )
            SnyggSpecDecl.PropertySet.Type.MULTIPLE_SETS -> {
                mapWithoutEmptyValuesOf(
                    "title" to props.meta.title,
                    "description" to props.meta.description,
                    "type" to "array",
                    "items" to props.objectSchema(),
                )
            }
        }
    }

    private fun SnyggSpecDecl.PropertySet.objectSchema(): Map<String, Any> {
        return mapWithoutEmptyValuesOf(
            "type" to "object",
            "patternProperties" to patternProperties
                .mapValues { (_, property) -> property.schema() }
                .mapKeys { (key, _) -> key.toString() },
            "properties" to properties.mapValues { (_, property) -> property.schema() },
            "additionalProperties" to false,
            "required" to properties.filter { it.value.required }.keys.toList(),
        )
    }

    private fun SnyggSpecDecl.Property.schema(): Map<String, Any> {
        return mapWithoutEmptyValuesOf(
            "title" to meta.title,
            "description" to meta.description,
            "oneOf" to oneOfList(encoders),
        )
    }

    private fun oneOfList(encoders: Set<SnyggValueEncoder>): List<Map<String, Any>> {
        return encoders.map { encoder ->
            mapOf(
                "\$ref" to "#/\$defs/${encoder.id()}",
            )
        }
    }

    private fun mapWithoutEmptyValuesOf(vararg pairs: Pair<String, Any>): Map<String, Any> {
        return mapOf(*pairs).filterValues { value ->
            when (value) {
                is String -> value.isNotBlank()
                is Map<*, *> -> value.isNotEmpty()
                is List<*> -> value.isNotEmpty()
                else -> true
            }
        }
    }

    private fun SnyggValueEncoder.id(): String {
        val className = this::class.simpleNameOrEnclosing() ?: error("could not resolve class name of $this")
        return className.replace("""([a-z])([A-Z])""".toRegex(), "$1-$2").lowercase()
    }

    private fun SnyggValueEncoder.schema(): Map<String, Any> {
        if (alternativeSpecs.isEmpty()) {
            return spec.schema()
        }
        return mapOf(
            "oneOf" to listOf(
                spec.schema(),
                *alternativeSpecs.map { it.schema() }.toTypedArray(),
            )
        )
    }

    private fun SnyggValueSpec.schema(): Map<String, Any> {
        if (this is SnyggKeywordValueSpec) {
            return mapOf(
                "type" to "string",
                if (keywords.size == 1) {
                    "const" to keywords[0]
                } else {
                    "enum" to keywords
                },
            )
        }
        return mapOf(
            "type" to "string",
            "pattern" to "^$parsePattern$",
        )
    }
}
